name = "TaSOI v2"
author = "stygigoth"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72360753741b671dca0ad298e8081b52edab62a6d8f87de424c15a948a483045"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
