name = "TaSOI 2"
author = "stygigoth"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2afbeb89263a7d199cce0e8ad6a454e2b8976e1a763033c94dd15c540e59d43b"

[versions]
minecraft = "1.19.2"
quilt = "0.26.1-beta.1"
